export { default as ForgotPasswordPage } from './forgot-password'
export { default as LoginPage } from './Login'
export { default as RegisterPage } from './Register'
export { default as ForgotPasswordAndResetPasswordPage } from './forgot-password-and-reset-password'
export { default as EmailVerificationPage } from './email-verification-page'
