export { default as LoginBackground } from './login-background.jpg'
export { default as USFlag } from './us-flag.png'
export { default as VIFlag } from './vi-flag.png'
export { default as OrderSuccess } from './order-success.svg'
export { default as Logo } from './logo.png'
export { default as TabLogo } from './tab-logo.png'
