export { default as LoginBackground } from './login-background.jpg'
export { default as USFlag } from './us-flag.png'
export { default as VIFlag } from './vi-flag.png'
export { default as OrderSuccess } from './order-success.svg'
export { default as Logo } from './logo.png'
export { default as LogoWhite } from './logo-white.png'
export { default as TabLogo } from './tab-logo.png'
export { default as Ga } from './ga.jpg'
export { default as Bia } from './bia.webp'
export { default as Tom } from './tom.jpg'
export { default as Com } from './com.png'
export { default as Store1 } from './store-1.webp'
export { default as Store2 } from './store-2.webp'
export { default as Store3 } from './store-3.webp'
export { default as Store4 } from './store-4.webp'
// export { default as LandingPageBackground } from './landing-page-background.jpg'
export { default as LandingPageBackground } from './landing-page-background.webp'
export { default as LandingPageBackgroundMobile } from './landing-page-background-mobile.jpg'
