export const QUERYKEY = {
  profile: ['profile'],
  branches: ['branches'],
  catalog: ['catalog'],
  productVariants: ['productVariants'],
  products: ['products'],
  vouchers: ['vouchers'],
  voucherGroups: ['voucherGroups'],
  vouchersForOrder: ['vouchersForOrder'],
  promotions: ['promotions'],
  banners: ['banners'],
  tables: ['tables'],
  roles: ['roles'],
  chefAreas: ['chefAreas'],
  chefOrders: ['chefOrders'],
  chefAreaProducts: ['chefAreaProducts'],
  notifications: ['notifications'],
  revenue: ['revenue'],
}
