export const ROUTE = {
  HOME: '/',
  PERSONAL_ACCOUNT: '/personal-account',
  ADMIN: '/admin',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/reset-password',
  ORDER_SUCCESS: '/order-success',
  VERIFY_EMAIL: '/verify-email', // Make sure this matches exactly with your URL path

  // System Routes
  OVERVIEW: '/system/overview',
  OVERVIEW_DETAIL: '/system/overview/detail',
  STAFF_BRANCH: '/system/branch',
  STAFF_PROFILE: '/system/profile',
  STAFF_MENU: '/system/menu',
  STAFF_CLIENT_VIEW: '/system/client-view',
  STAFF_CHECKOUT_ORDER: '/checkout-order',
  STAFF_ORDER_PAYMENT: '/system/payment',
  STAFF_ORDER_MANAGEMENT: '/system/order-management',
  STAFF_CHEF_ORDER: '/system/chef-order',
  STAFF_ORDER_HISTORY: '/system/order-history',
  // STAFF_UPDATE_ORDER: '/system/update-order',
  STAFF_ORDER_PREPARATION: '/order-preparation',
  STAFF_TABLE_MANAGEMENT: '/system/table',
  STAFF_PRODUCT_MANAGEMENT: '/system/product',
  STAFF_MENU_MANAGEMENT: '/system/menu-management',
  STAFF_DELIVERY_MANAGEMENT: '/delivery-management',
  STAFF_WALLET_MANAGEMENT: '/system/wallet-management',
  STAFF_LOG_MANAGEMENT: '/system/log',
  STAFF_USER_MANAGEMENT: '/system/staff',
  STAFF_CUSTOMER_MANAGEMENT: '/system/customers',
  STAFF_ROLE_MANAGEMENT: '/system/role',
  STAFF_BANK_CONFIG: '/system/bank-config',
  STAFF_STATIC_PAGE: '/system/static-page',
  STAFF_VOUCHER: '/system/voucher',
  STAFF_PROMOTION: '/system/promotion',
  STAFF_CHEF_AREA_MANAGEMENT: '/system/area',
  STAFF_BANNER: '/system/banner',
  STAFF_CONFIG: '/system/config',

  //Client Routes
  CLIENT_HOME: '/',
  CLIENT_MENU: '/menu',
  CLIENT_MENU_ITEM: '/menu-item',
  CLIENT_CART: '/cart',
  CLIENT_CHECKOUT_ORDER: '/checkout-order',
  CLIENT_PAYMENT: '/payment',
  CLIENT_ORDER_HISTORY: '/history',
  CLIENT_UPDATE_ORDER: '/update-order',
  CLIENT_PROFILE: '/profile',
  // CLIENT_VOUCHER: '/voucher',

  // General Routes
  ABOUT: '/about',
  CONTACT: '/contact',
  HELP: '/help',
  POLICY: '/policy',
  SECURITY: '/security',
  DOCS: '/docs',

  ADMIN_CONFIG: 'system/config',
  ADMIN_VOUCHER: 'system/voucher',
  ADMIN_PROMOTION: 'system/promotion',
  ADMIN_BANNER: 'system/banner',
}
