export const ROUTE = {
  HOME: '/',
  PERSONAL_ACCOUNT: '/personal-account',
  ADMIN: '/admin',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/reset-password',
  ORDER_SUCCESS: '/order-success',

  // System Routes
  OVERVIEW: '/system/overview',
  OVERVIEW_DETAIL: '/system/overview/detail',
  STAFF_BRANCH: '/system/branch',
  STAFF_PROFILE: '/system/profile',
  STAFF_MENU: '/system/menu',
  STAFF_CHECKOUT_ORDER: '/checkout-order',
  STAFF_ORDER_PAYMENT: '/system/payment',
  STAFF_ORDER_MANAGEMENT: '/order-management',
  STAFF_ORDER_HISTORY: '/system/order-history',
  STAFF_ORDER_PREPARATION: '/order-preparation',
  STAFF_TABLE_MANAGEMENT: '/system/table',
  STAFF_PRODUCT_MANAGEMENT: '/system/product',
  STAFF_MENU_MANAGEMENT: '/system/menu-management',
  STAFF_DELIVERY_MANAGEMENT: '/delivery-management',
  STAFF_WALLET_MANAGEMENT: '/wallet-management',
  STAFF_LOG_MANAGEMENT: '/log',
  STAFF_USER_MANAGEMENT: '/system/staff',
  STAFF_CUSTOMER_MANAGEMENT: '/system/customers',
  STAFF_BANK_CONFIG: '/bank-config',
  STAFF_STATIC_PAGE: '/system/static-page',
  STAFF_BANNER: '/system/banner',

  //Client Routes
  CLIENT_HOME: '/',
  CLIENT_MENU: '/menu',
  CLIENT_MENU_ITEM: '/menu-item',
  CLIENT_CART: '/cart',
  CLIENT_CHECKOUT_ORDER: '/checkout-order',
  CLIENT_PAYMENT: '/payment',
  CLIENT_ORDER_HISTORY: '/history',
  CLIENT_UPDATE_ORDER: '/update-order',
  CLIENT_PROFILE: '/profile',
  CLIENT_VOUCHER: '/voucher',

  // General Routes
  ABOUT: '/about',
  CONTACT: '/contact',
  HELP: '/help',
  POLICY: '/policy',
  DOCS: '/docs',

  ADMIN_CONFIG: '/config',
  ADMIN_VOUCHER: '/voucher',
  ADMIN_PROMOTION: '/promotion',
  ADMIN_BANNER: '/banner',
}
