export enum SystemConfigKey {
  FRONTEND_URL = 'FRONTEND_URL',
  ROBOT_ID = 'ROBOT_ID',
  ROBOT_API_URL = 'ROBOT_API_URL',
  ACB_API_URL = 'ACB_API_URL',
  AUTH_ACB_API_URL = 'AUTH_ACB_API_URL',
  FOLDER_ID = 'FOLDER_ID',
}
