export { default as CustomerInformation } from './customer-information'
export { default as OrderItemDetail } from './order-item-detail'
export { default as OrderItemList } from './order-item-list'
export { default as OrderHistoryPage } from './order-history-page'
export { default as OrderManagementPage } from './order-management-page'
export { default as OrderWaitListCounting } from './order-wait-list-counting'
export { default as TotalOrders } from './total-orders'
